/*
 * File: app/store/MyArrayStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.store.MyArrayStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        data: [
            {
                Intensity: 'Sad zero',
                Value: 60
            },
            {
                Intensity: 'Sad one',
                Value: 10
            },
            {
                Intensity: 'Sad two',
                Value: 20
            },
            {
                Intensity: 'Sad three',
                Value: 40
            },
            {
                Intensity: 'Sad four',
                Value: 45
            },
            {
                Intensity: 'Sad five',
                Value: 40
            },
            {
                Intensity: 'Happy zero',
                Value: 60
            },
            {
                Intensity: 'Happy one',
                Value: 40
            },
            {
                Intensity: 'Happy two',
                Value: 0
            },
            {
                Intensity: 'Happy three',
                Value: 30
            },
            {
                Intensity: 'Happy four',
                Value: 4
            },
            {
                Intensity: 'Happy five',
                Value: 14
            },
            
        ],
        storeId: 'MyArrayStore',
        fields: [
            {
                name: 'Intensity'
            },
            {
                name: 'Value'
            }
        ]
    }
});