/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.MyNavigationView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mynavigationview',

    requires: [
        'Ext.Panel',
        'Ext.Img',
        'Ext.Button',
        'Ext.Map',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.IndexBar',
        'Ext.navigation.Bar'
    ],

    config: {
        style: 'background-color: #FFF',
        items: [
            {
                xtype: 'container',
                docked: 'top',
                items: [
                    {
                        xtype: 'panel',
                        centered: false,
                        docked: 'top',
                        maxHeight: 100,
                        style: 'background-color:#006db9',
                        layout: {
                            type: 'hbox',
                            align: 'start',
                            pack: 'end'
                        },
                        items: [
                            {
                                xtype: 'image',
                                flex: 1,
                                maxWidth: 100,
                                minHeight: 75,
                                style: 'background-color:#FFFFFF',
                                src: 'transafe_logo.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                maxWidth: 200,
                                minHeight: 75,
                                top: '',
                                ui: 'action',
                                icon: 'icon_listview.png',
                                iconAlign: 'center',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                maxWidth: 200,
                                minHeight: 75,
                                ui: 'action',
                                icon: 'icon_mapview.png',
                                iconAlign: 'center'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                maxWidth: 200,
                                minHeight: 75,
                                ui: 'action',
                                icon: 'icon_login.png',
                                iconAlign: 'center'
                            }
                        ]
                    },
                    {
                        xtype: 'map',
                        height: 200,
                        mapOptions: {
                            
                        },
                        useCurrentLocation: true
                    }
                ]
            },
            {
                xtype: 'list',
                title: 'Locations NearBy',
                itemId: 'mylist',
                hideOnMaskTap: false,
                allowDeselect: true,
                itemTpl: [
                    '<div>{name}</div>'
                ],
                store: 'FS',
                grouped: true,
                indexBar: true
            }
        ],
        navigationBar: {
            docked: 'top'
        }
    }

});