/*
 * File: app/view/MyPanel21.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.MyPanel21', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Map'
    ],

    config: {
        items: [
            {
                xtype: 'map',
                centered: true,
                height: '100%',
                id: 'map2',
                itemId: 'mymap2',
                styleHtmlContent: true,
                width: '100%',
                mapOptions: {
                    mapTypeId: google.maps.MapTypeId.HYBRID
                },
                useCurrentLocation: true
            }
        ]
    },

    initialize: function() {
          this.callParent();
        console.log('you are here: '+ lt +',' + lng);
                        //this.callParent();
                        var gMap1 = Ext.getCmp('map2');
                //add traffic layer
                   var trafficLayer = new google.maps.TrafficLayer();
                   trafficLayer.setMap(gMap1.getMap());


                           // drop map marker
                           var mymarker = new google.maps.Marker({
                            map: gMap1.getMap(),
                            animation: google.maps.Animation.DROP,
                               position: new google.maps.LatLng(lt,lng),
                               title: "You are here",
                            //icon: 'transafe_logo.png'
                               icon: 'http://www.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png'
                           });

                    var contentString = '<div class = "MarkerPopUp" style="width: 100px;"><div class = "MarkerContext" onclick="Ext.Viewport.setActiveItem(\'surveypanel\',{type: \'slide\',direction: \'left\'});">You are Here!</div></div>';

                                var infowindow = new google.maps.InfoWindow({
                                  content: contentString,
                                    maxWidth: 700
                              });


                                google.maps.event.addListener(mymarker, 'click', function() {
                                    infowindow.open(gMap1.getMap(),mymarker);
                              });


                //Ajax Request for foursquare locations
                   var ajaxRequest;  // The variable that makes Ajax possible!

                	try{
                		// Opera 8.0+, Firefox, Safari
                		ajaxRequest = new XMLHttpRequest();
                	} catch (e){
                		// Internet Explorer Browsers
                		try{
                			ajaxRequest = new ActiveXObject("Msxml2.XMLHTTP");
                		} catch (e) {
                			try{
                				ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
                			} catch (e){
                				// Something went wrong
                				alert("Your browser broke!");
                				return false;
                			}
                		}
                	}
                	// Create a function that will receive data sent from the server
                	ajaxRequest.onreadystatechange = function(){
                		if(ajaxRequest.readyState == 4){

                            var data =  JSON.parse(ajaxRequest.responseText);
                			//alert(["venues"]);
                            var i=0;

                            var marker = new Array(data.response.venues.length);
                            var contentString = new Array(data.response.venues.length);
                            var infowindow = new Array(data.response.venues.length);

                            for(i=0;i<data.response.venues.length;i++)
                            {
                            contentString[i] = '<div class = "MarkerPopUp" style="width: 100px;"><div class = "MarkerContext" onclick="Ext.Viewport.setActiveItem(\'surveypanel\',{type: \'slide\',direction: \'left\'});">'+data.response.venues[i].name+'</div></div>';
                            infowindow[i]= new google.maps.InfoWindow({
                                  content: contentString[i],
                                    maxWidth: 700
                              });
                            marker[i] = new google.maps.Marker({
                            map: gMap1.getMap(),
                            animation: google.maps.Animation.DROP,
                            position: new google.maps.LatLng(data.response.venues[i].location.lat,data.response.venues[i].location.lng),
                            title: data.response.venues[i].name,
                            icon: 'http://www.google.com/intl/en_us/mapfiles/ms/micons/blue-dot.png'
                           });
                                (function(i){
                                google.maps.event.addListener(marker[i], 'click', function() {
                                    infowindow[i].open(gMap1.getMap(),marker[i]);
                                    var j=0;
                                    for(j=0;j<data.response.venues.length;j++){
                                        (function(j){
                                            if(i!=j)
                                            infowindow[j].close();
                                                  })(j);

                                    }
                              });
                              })(i);
                            }
                		}
                	};


                	ajaxRequest.open("GET", "https://api.foursquare.com/v2/venues/search?ll="+lt+","+lng+"&client_id=FHGRALBMIKR04JREC02GPFOJFXNEDXVFJ0LCUM5J025YRFHY&client_secret=2BTYTCA4NIKM0EXVVKQ2NFQRXYPJ252RO4EDB0GVLTLMOLBI&v=20140130", true);
                	ajaxRequest.send(null);

    }

});