/*
 * File: app/view/statTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.statTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.stattabpanel',

    requires: [
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie',
        'Ext.chart.interactions.Rotate',
        'Ext.chart.Legend',
        'Ext.Label',
        'Ext.Panel',
        'Ext.Img',
        'Ext.Button'
    ],

    config: {
        tabBarPosition: 'bottom',
        id: 'stattabpanel',
        items: [
            {
                xtype: 'container',
                title: 'Happy',
                layout: 'fit',
                scrollable: true,
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        scrollable: true,
                        items: [
                            {
                                xtype: 'polar',
                                id: 'happyPie',
                                maxWidth: '50%',
                                colors: [
                                    '#FFB8BF',
                                    '#FF8F9A',
                                    '#FF707E',
                                    '#FF4D4F',
                                    '#FF3D3F',
                                    '#C2000C',
                                    '#BDFFBD',
                                    '#70FF70',
                                    '#4CFF4D',
                                    '#67DA68',
                                    '#01B703',
                                    '#036D04'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'happyLegend'
                                }
                            },
                            {
                                xtype: 'label',
                                html: 'default location',
                                id: 'statLocationHappy'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Excited',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        scrollable: true,
                        items: [
                            {
                                xtype: 'polar',
                                id: 'excitedPie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'excitedLegend'
                                }
                            },
                            {
                                xtype: 'label',
                                html: 'default location',
                                id: 'statLocationExcited'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Safe',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'polar',
                                id: 'safePie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'safeLegend'
                                }
                            },
                            {
                                xtype: 'label',
                                html: 'default location',
                                id: 'statLocationSafe'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Peaceful',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'polar',
                                id: 'peacefulPie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'peacefulLegend'
                                }
                            },
                            {
                                xtype: 'label',
                                html: 'default location',
                                id: 'statLocationPeaceful'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                centered: false,
                docked: 'top',
                maxHeight: 100,
                style: 'background-color:#006db9',
                layout: {
                    type: 'hbox',
                    align: 'start',
                    pack: 'end'
                },
                items: [
                    {
                        xtype: 'image',
                        flex: 1,
                        height: 201,
                        maxHeight: 75,
                        style: 'background-color:#FFFFFF',
                        src: 'transafe_logo.png'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.setActiveItem('mynavigationview',{
                                type: "slide",
                                direction: "left"
                            });
                        },
                        flex: 1,
                        cls: '@include icon("list", "l");',
                        id: 'listViewButton4',
                        minHeight: 75,
                        ui: 'action',
                        iconAlign: 'center',
                        iconCls: 'list',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {

                        },
                        flex: 1,
                        disabled: true,
                        minHeight: 75,
                        ui: 'action',
                        iconAlign: 'center',
                        iconCls: 'maps'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            console.log('prev view');
                            console.log(Ext.Viewport.getActiveItem().getId());
                            localStorage.setItem('prevView', Ext.Viewport.getActiveItem().getId());
                            Ext.Viewport.setActiveItem('signuppanel',{
                                type: "slide",
                                direction: "left"
                            });
                        },
                        flex: 1,
                        minHeight: 75,
                        top: '',
                        ui: 'action',
                        iconAlign: 'center',
                        iconCls: 'user'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent(arguments);
        var pieToHide;
        var pieToShow;
        var legendToHide;
        var legendToShow;
        console.log(localStorage.getItem('ifLogged'));
        if(localStorage.getItem('ifLogged')== 'Invalid User' || localStorage.getItem('ifLogged')=== ''|| localStorage.getItem('ifLogged')=== undefined || localStorage.getItem('ifLogged') === null){
            console.log("anonimous");
            Ext.getCmp('happyPie').hide();
            Ext.getCmp('happyLegend').hide();
            Ext.getCmp('excitedPie').hide();
            Ext.getCmp('excitedLegend').hide();
            Ext.getCmp('safePie').hide();
            Ext.getCmp('safeLegend').hide();
            Ext.getCmp('peacefulPie').hide();
            Ext.getCmp('peacefulLegend').hide();
        }
        else{
            console.log("logged in");
            Ext.getCmp('happyPie').show();
            Ext.getCmp('happyLegend').show();
            Ext.getCmp('excitedPie').show();
            Ext.getCmp('excitedLegend').show();
            Ext.getCmp('safePie').show();
            Ext.getCmp('safeLegend').show();
            Ext.getCmp('peacefulPie').show();
            Ext.getCmp('peacefulLegend').show();
        }
    }

});