/*
 * File: app/view/statistics.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.statistics', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie',
        'Ext.chart.interactions.Rotate'
    ],

    config: {
        items: [
            {
                xtype: 'polar',
                colors: [
                    '#115fa6',
                    '#94ae0a',
                    '#a61120',
                    '#ff8809',
                    '#ffd13e',
                    '#a61187',
                    '#24ad9a',
                    '#7c7474',
                    '#a66111'
                ],
                series: [
                    {
                        type: 'pie',
                        labelField: 'x',
                        xField: 'y2'
                    }
                ],
                interactions: [
                    {
                        type: 'rotate'
                    }
                ]
            }
        ]
    }

});