/*
 * File: app/view/statTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.statTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.stattabpanel',

    requires: [
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie',
        'Ext.chart.interactions.Rotate',
        'Ext.chart.Legend'
    ],

    config: {
        tabBarPosition: 'bottom',
        id: 'stattabpanel',
        items: [
            {
                xtype: 'container',
                title: 'Happy',
                layout: 'fit',
                scrollable: true,
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        scrollable: true,
                        items: [
                            {
                                xtype: 'polar',
                                id: 'happyPie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'happyLegend'
                                }
                            },
                            {
                                xtype: 'polar',
                                id: 'happyPie1',
                                margin: '0 0 0 50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'anonimousArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Feeling',
                                        xField: 'TotalValue'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'happyPie1Legend'
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Excited',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        scrollable: true,
                        items: [
                            {
                                xtype: 'polar',
                                id: 'excitedPie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'excitedLegend'
                                }
                            },
                            {
                                xtype: 'polar',
                                id: 'excitedPie1',
                                margin: '0 0 0 50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'anonimousArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Feeling',
                                        xField: 'TotalValue'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'excitedPie1Legend'
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Safe',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'polar',
                                id: 'safePie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'safeLegend'
                                }
                            },
                            {
                                xtype: 'polar',
                                id: 'safePie1',
                                margin: '0 0 0 50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'anonimousArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Feeling',
                                        xField: 'TotalValue'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'safePie1Legend'
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Peaceful',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'polar',
                                id: 'peacefulPie',
                                maxWidth: '50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'MyArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Intensity',
                                        xField: 'Value'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'peacefulLegend'
                                }
                            },
                            {
                                xtype: 'polar',
                                id: 'peacfulPie1',
                                margin: '0 0 0 50%',
                                colors: [
                                    '#115fa6',
                                    '#94ae0a',
                                    '#a61120',
                                    '#ff8809',
                                    '#ffd13e',
                                    '#a61187',
                                    '#24ad9a',
                                    '#7c7474',
                                    '#a66111'
                                ],
                                store: 'anonimousArrayStore',
                                series: [
                                    {
                                        type: 'pie',
                                        labelField: 'Feeling',
                                        xField: 'TotalValue'
                                    }
                                ],
                                interactions: [
                                    {
                                        type: 'rotate'
                                    }
                                ],
                                legend: {
                                    xtype: 'legend',
                                    id: 'peacefulPie1Legend'
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent(arguments);
        var pieToHide;
        var pieToShow;
        var legendToHide;
        var legendToShow;
        console.log(localStorage.getItem('ifLogged'));
        if(localStorage.getItem('ifLogged')== 'Invalid User' || localStorage.getItem('ifLogged')=== ''|| localStorage.getItem('ifLogged')=== undefined || localStorage.getItem('ifLogged') === null){
            console.log("anonimous");
            Ext.getCmp('happyPie').hide();
            Ext.getCmp('happyLegend').hide();
            Ext.getCmp('excitedPie').hide();
            Ext.getCmp('excitedLegend').hide();
            Ext.getCmp('safePie').hide();
            Ext.getCmp('safeLegend').hide();
            Ext.getCmp('peacefulPie').hide();
            Ext.getCmp('peacefulLegend').hide();
        }
        else{
            console.log("logged in");
            Ext.getCmp('happyPie').show();
            Ext.getCmp('happyLegend').show();
            Ext.getCmp('excitedPie').show();
            Ext.getCmp('excitedLegend').show();
            Ext.getCmp('safePie').show();
            Ext.getCmp('safeLegend').show();
            Ext.getCmp('peacefulPie').show();
            Ext.getCmp('peacefulLegend').show();
        }
    }

});