/*
 * File: app/view/surveyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.surveyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.surveypanel',

    requires: [
        'Ext.Panel',
        'Ext.Img',
        'Ext.Button',
        'Ext.Label',
        'Ext.field.Slider'
    ],

    config: {
        id: 'surveypanel',
        style: 'background-color: #FFF',
        scrollable: true,
        items: [
            {
                xtype: 'container',
                docked: 'top',
                items: [
                    {
                        xtype: 'panel',
                        centered: false,
                        docked: 'top',
                        maxHeight: 100,
                        style: 'background-color:#006db9',
                        layout: {
                            type: 'hbox',
                            align: 'start',
                            pack: 'end'
                        },
                        items: [
                            {
                                xtype: 'image',
                                flex: 1,
                                height: 201,
                                maxHeight: 75,
                                style: 'background-color:#FFFFFF',
                                src: 'transafe_logo.png'
                            },
                            {
                                xtype: 'button',
                                handler: function(button, e) {
                                    Ext.Viewport.setActiveItem('mynavigationview',{
                                        type: "slide",
                                        direction: "left"
                                    });
                                },
                                flex: 1,
                                cls: '@include icon("list", "l");',
                                id: 'listViewButton1',
                                minHeight: 75,
                                ui: 'action',
                                iconAlign: 'center',
                                iconCls: 'list',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                handler: function(button, e) {

                                },
                                flex: 1,
                                disabled: true,
                                minHeight: 75,
                                ui: 'action',
                                iconAlign: 'center',
                                iconCls: 'maps'
                            },
                            {
                                xtype: 'button',
                                handler: function(button, e) {
                                    console.log('prev view');
                                    console.log(Ext.Viewport.getActiveItem().getId());
                                    localStorage.setItem('prevView', Ext.Viewport.getActiveItem().getId());
                                    Ext.Viewport.setActiveItem('signuppanel',{
                                        type: "slide",
                                        direction: "left"
                                    });
                                },
                                flex: 1,
                                minHeight: 75,
                                top: '',
                                ui: 'action',
                                iconAlign: 'center',
                                iconCls: 'user'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            //Ext.Viewport.add(Ext.create('TranSafe.view.MyNavigationView'));
                            Ext.Viewport.setActiveItem('signuppanel',{
                                type: "slide",
                                direction: "left"
                            });

                        },
                        docked: 'right',
                        hidden: true,
                        id: 'signUpBtn',
                        ui: 'action-round',
                        text: 'Sign up'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            //Ext.Viewport.add(Ext.create('TranSafe.view.MyNavigationView'));
                            Ext.Viewport.setActiveItem('signinpanel',{
                                type: "slide",
                                direction: "left"
                            });

                        },
                        docked: 'right',
                        hidden: true,
                        id: 'signInBtn',
                        ui: 'action-round',
                        text: 'Sign in'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            localStorage.setItem('ifLogged', '');
                            localStorage.setItem('username','');
                            console.log('signing out');
                            Ext.Viewport.setActiveItem('surveypanel',{
                                type: "slide",
                                direction: "left"
                            });
                            window.location.reload();
                        },
                        docked: 'right',
                        hidden: true,
                        id: 'signOutBtn',
                        ui: 'action-round',
                        text: 'Sign out'
                    },
                    {
                        xtype: 'label',
                        docked: 'right',
                        hidden: true,
                        html: 'Hello, username',
                        id: 'greetingLabel'
                    }
                ]
            },
            {
                xtype: 'label',
                docked: 'top',
                html: 'Venue: ',
                id: 'venueLblSurvey'
            },
            {
                xtype: 'container',
                scrollable: true,
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'container',
                                docked: 'top',
                                margin: '10 0 10 0',
                                items: [
                                    {
                                        xtype: 'container',
                                        docked: 'top',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 70,
                                                id: 'sadFacePic',
                                                styleHtmlContent: true,
                                                width: 70,
                                                src: 'Emoticons/centered/sad.png'
                                            },
                                            {
                                                xtype: 'image',
                                                docked: 'right',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/happy.png'
                                            },
                                            {
                                                xtype: 'sliderfield',
                                                docked: 'top',
                                                id: 'sliderHappySad',
                                                width: '',
                                                clearIcon: false,
                                                label: '',
                                                labelAlign: 'top',
                                                value: [
                                                    0
                                                ],
                                                maxValue: 5,
                                                minValue: -5
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Sad',
                                        padding: '0 0 0 10'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        html: 'Happy',
                                        padding: '0 10 0 0'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                margin: '10 0 0 0',
                                width: '',
                                items: [
                                    {
                                        xtype: 'container',
                                        docked: 'top',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'right',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/excited.png'
                                            },
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/bored.png'
                                            },
                                            {
                                                xtype: 'sliderfield',
                                                docked: 'top',
                                                id: 'sliderExcitedBored',
                                                width: '',
                                                clearIcon: false,
                                                label: '',
                                                labelAlign: 'top',
                                                value: [
                                                    0
                                                ],
                                                maxValue: 5,
                                                minValue: -5
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Bored',
                                        padding: '0 0 0 10'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        html: 'Excited',
                                        padding: '0 10 0 0'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                margin: '10 0 10 0',
                                items: [
                                    {
                                        xtype: 'container',
                                        docked: 'top',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'right',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/safe.png'
                                            },
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/scared.png'
                                            },
                                            {
                                                xtype: 'sliderfield',
                                                docked: 'top',
                                                id: 'sliderSafeScared',
                                                width: '',
                                                clearIcon: false,
                                                label: '',
                                                labelAlign: 'top',
                                                value: [
                                                    0
                                                ],
                                                maxValue: 5,
                                                minValue: -5
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Scared',
                                        padding: '0 0 0 10'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        html: 'Safe',
                                        padding: '0 10 0 0'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                margin: '10 0 0 0',
                                items: [
                                    {
                                        xtype: 'container',
                                        docked: 'top',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'right',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/peaceful.png'
                                            },
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 70,
                                                width: 70,
                                                src: 'Emoticons/centered/angry.png'
                                            },
                                            {
                                                xtype: 'sliderfield',
                                                docked: 'top',
                                                id: 'sliderPeacefulAngry',
                                                width: '',
                                                clearIcon: false,
                                                label: '',
                                                labelAlign: 'top',
                                                value: [
                                                    0
                                                ],
                                                maxValue: 5,
                                                minValue: -5
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Angry',
                                        padding: '0 0 0 10'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        html: 'Peaceful',
                                        padding: '0 10 0 0'
                                    }
                                ]
                            },
                            {
                                xtype: 'label'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.setActiveItem('comfortPanel',{
                                type: "slide",
                                direction: "left"
                            });


                        },
                        itemId: 'mybutton2',
                        ui: 'forward',
                        text: 'Next'
                    }
                ]
            }
        ]
    }

});