/*
 * File: app/view/surveyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.surveyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.surveypanel',

    requires: [
        'Ext.Container',
        'Ext.Button',
        'Ext.Label',
        'Ext.Img',
        'Ext.field.Slider'
    ],

    config: {
        id: 'surveyPanel',
        style: 'background-color: #FFF',
        items: [
            {
                xtype: 'container',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            //Ext.Viewport.add(Ext.create('TranSafe.view.MyNavigationView'));
                            Ext.Viewport.setActiveItem('signuppanel',{
                                type: "slide",
                                direction: "left"
                            });

                        },
                        docked: 'right',
                        id: 'signUpBtn',
                        ui: 'action-round',
                        text: 'Sign up'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            //Ext.Viewport.add(Ext.create('TranSafe.view.MyNavigationView'));
                            Ext.Viewport.setActiveItem('signinpanel',{
                                type: "slide",
                                direction: "left"
                            });

                        },
                        docked: 'right',
                        id: 'signInBtn',
                        ui: 'action-round',
                        text: 'Sign in'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            localStorage.setItem('ifLogged', 0);
                            localStorage.setItem('username','');
                            console.log('signing out');
                            Ext.Viewport.setActiveItem('surveypanel',{
                                type: "slide",
                                direction: "left"
                            });
                            window.location.reload();
                        },
                        docked: 'right',
                        hidden: true,
                        id: 'signOutBtn',
                        ui: 'action-round',
                        text: 'Sign out'
                    },
                    {
                        xtype: 'label',
                        docked: 'right',
                        hidden: true,
                        html: 'Hello, username',
                        id: 'greetingLabel'
                    }
                ]
            },
            {
                xtype: 'label',
                docked: 'top',
                html: 'Venue: ',
                id: 'venueLblSurvey'
            },
            {
                xtype: 'container',
                docked: 'top',
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                styleHtmlContent: true,
                                width: 50,
                                src: 'Emoticons/emotion_sad.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_happy_notext.png'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                id: 'sliderHappySad',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    0
                                ],
                                maxValue: 5,
                                minValue: -5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        width: '',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_excited.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_bored.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                id: 'sliderExcitedBored',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    0
                                ],
                                maxValue: 5,
                                minValue: -5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_safe.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_scared.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                id: 'sliderSafeScared',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    0
                                ],
                                maxValue: 5,
                                minValue: -5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_peaceful.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_angry.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                id: 'sliderPeacefulAngry',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    0
                                ],
                                maxValue: 5,
                                minValue: -5
                            }
                        ]
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.setActiveItem('comfortPanel',{
                                type: "slide",
                                direction: "left"
                            });


                        },
                        docked: 'bottom',
                        itemId: 'mybutton2',
                        ui: 'forward',
                        text: 'Next'
                    }
                ]
            }
        ]
    }

});